site_name: test-mkdocks
site_url: https://experimentsinhonesty.github.io/test-mkdocs/
repo_url: https://github.com/experimentsinhonesty/test-mkdocs
edit_uri: edit/main/docs

theme:
  logo: assets/logo.png
  name: material
  palette:
    scheme: Blue
  features:
    - navigation.tabs
    - navigation.tabs.sticky
extra_css:
  - stylesheets/extra.css
