site_name: GreenEarthOS
site_url: https://greenearthos.org
repo_url: https://github.com/hackforla/GreenEarthOS/
edit_uri: edit/main/docs

theme:
  name: material
  features:
    - navigation.tabs
  palette:
    primary: "red"
    accent: "blue"
